version: '3'

volumes:
  db-data:

services:
  app:
    build: .
    ports:
      - '8890:8888'
    volumes:
      - '.:/python_postgres'
    environment: 
      - 'DATABASE_PASSWORD=postgres'
    #user: '1000:1000'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links:
      - db
  
  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
